server:
  port: 3333
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  application:
    name: auth-server-sso
  liquibase:
    enabled: true
    change-log: classpath:database/db.changelog.yml
    contexts: prod
  mvc:
    static-path-pattern: /static/**
    cors:
      configs:
          pattern: /**
          allowed-origins: "http://localhost:4444, http://localhost:4311, http://localhost:5555"
          allowed-headers: "*"
          exposed-headers: "auth-server-header"
          allowed-methods: "*"
          allow-credentials: true
  web:
    resources:
      static-locations: classpath:static
  security:
    oauth2:
      authorizationserver:
        issuer-uri: http://localhost:3333
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-server-test-platform?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
    username: postgres
    password: 45567899
    driver-class-name: "org.postgresql.Driver"
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 15
      minimum-idle: 10
      initialization-fail-timeout: 1
      leak-detection-threshold: 0
      pool-name: "[HikariPool-auth-server]"
      register-mbeans: true
  jpa:
    show-sql: true
    dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddlAuto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        jdbc:
#          lob:
#            non_contextual_creation: true

